name: pyChat
version: '1.3.5'
main: de.proxyfile.pychat.PyChat
api-version: '1.18'
authors: [ ProxyFile ]
description: Lightweight chat system for easy communication.
depends: [Luckperms]
commands:
  toggle:
    description: You can do /pychat help to see more!
  pychat:
    description: You can do /pychat help to see more!
